import json
import re
from pathlib import Path

preamble = f"// This file was generated by {Path(__file__).name}"


def split_words(string: str) -> list[str]:
    return re.sub("[^0-9a-zA-Z]", " ", string).split()


def camel_case(string: str) -> str:
    return "".join(w.lower() if i == 0 else w.capitalize() for i, w in enumerate(split_words(string)))


def pascal_case(string: str) -> str:
    return "".join(w.lower().capitalize() for w in split_words(string))


def title_case(string: str) -> str:
    return " ".join(w[0].upper() + w[1:] for w in string.split())


def snake_case(string: str) -> str:
    return "_".join(w.lower() for w in split_words(string))


# Load Settings.json
key_values = json.loads(Path("Settings.json").read_text())

includes = key_values["includes"]
settings = key_values["settings"]

preserveds = [s.get("preserved") for s in settings]

for index in range(1, len(preserveds)):
    if preserveds[index] and not preserveds[index - 1]:
        raise Exception("Preserved settings must be contiguous")

# Generate Ximu3Definitions.h
includes = "\n".join(f"#include {i}" for i in includes)

values = "\n".join(f"    {s['declaration'].replace('name', camel_case(s['name']))};" for s in settings)

index = "\n".join(f"    Ximu3SettingsIndex{pascal_case(s['name'])}," for s in settings)

contents = f"""\
{preamble}

#ifndef XIMU3_DEFINITIONS_H
#define XIMU3_DEFINITIONS_H

{includes}

#define XIMU3_MAX_KEY_LENGTH ({max(len(s["name"]) for s in settings)})

#define XIMU3_NUMBER_OF_SETTINGS ({len(settings)})

#define XIMU3_TERMINATION '\\n'

#define XIMU3_TERMINATION_STRING "\\n"

#define XIMU3_MUX_ID '^'

#define XIMU3_MUX_BROADCAST XIMU3_MUX_ID

typedef enum {{
    Ximu3ResultOk,
    Ximu3ResultError,
}} Ximu3Result;

typedef struct {{
{values}
}} Ximu3SettingsValues;

typedef enum {{
{index}
}} Ximu3SettingsIndex;

Ximu3Result Ximu3SettingsIndexFrom(Ximu3SettingsIndex * const index, const int integer);

#endif
"""

Path("Ximu3Definitions.h").write_text(contents)

# Generate Ximu3Definitions.c
cases = "\n".join(
    f"""\
        case Ximu3SettingsIndex{pascal_case(s["name"])}:
            *index = Ximu3SettingsIndex{pascal_case(s["name"])};
            break;"""
    for s in settings
)

contents = f"""\
{preamble}

#include "Ximu3Definitions.h"

Ximu3Result Ximu3SettingsIndexFrom(Ximu3SettingsIndex * const index, const int integer) {{
    switch (integer) {{
{cases}
        default:
            return Ximu3ResultError;
    }}
    return Ximu3ResultOk;
}}
"""

Path("Ximu3Definitions.c").write_text(contents)

# Generate Metadata.h
type = ("String" if "char name[" in s["declaration"] else title_case(s["declaration"].split()[0].replace("_t", "")) for s in settings)
type = list(set(type))  # remove duplicates
type.sort()  # sort alphabetically
type = "\n".join(f"    MetadataType{t}," for t in type)

contents = f"""\
{preamble}

#ifndef METADATA_H
#define METADATA_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "Ximu3Definitions.h"
#include "Ximu3Settings.h"

typedef enum {{
{type}
}} MetadataType;

typedef struct {{
    const char* const name;
    const char* const key;
    void* const value;
    const MetadataType type;
    const size_t size;
    const void* const defaultValue;
    const bool preserved;
    const bool readOnly;
    bool* const applied;
}} Metadata;

Metadata MetadataGet(Ximu3Settings * const settings, const Ximu3SettingsIndex index);

#endif
"""

Path("Metadata.h").write_text(contents)

# Generate Metadata.c
names = "\n".join(f'    "{title_case(s["name"])}",' for s in settings)

keys = "\n".join(f'    "{snake_case(s["name"])}",' for s in settings)

types = "\n".join(f"    MetadataType{'String' if 'char name[' in s['declaration'] else title_case(s['declaration'].split()[0].replace('_t', ''))}," for s in settings)

sizes = "\n".join(f"    sizeof (((Ximu3SettingsValues *) 0)->{camel_case(s['name'])})," for s in settings)

defaults = "\n".join(f"    (void*) (&({s['declaration'].replace(' name', '')}) {s['default']})," for s in settings)

preserveds = "\n".join(f"    {str(bool(s.get('preserved'))).lower()}," for s in settings)

read_onlys = "\n".join(f"    {str(bool(s.get('preserved')) or bool(s.get('read-only'))).lower()}," for s in settings)

template = """\
        case label:
            return &settings->values.member;
"""
cases = "".join(template.replace("label", f"Ximu3SettingsIndex{pascal_case(s['name'])}").replace("member", camel_case(s["name"])) for s in settings)

contents = f"""\
{preamble}

#include "Metadata.h"

static const char* const names[] = {{
{names}
}};

static const char* const keys[] = {{
{keys}
}};

const MetadataType types[] = {{
{types}
}};

const size_t sizes[] = {{
{sizes}
}};

const void* const defaults[] = {{
{defaults}
}};

const bool preserveds[] = {{
{preserveds}
}};

const bool readOnlys[] = {{
{read_onlys}
}};

static void* GetValue(Ximu3Settings * const settings, const Ximu3SettingsIndex index) {{
    switch (index) {{
{cases}
    }}
    return NULL; // avoid compiler warning
}}

Metadata MetadataGet(Ximu3Settings * const settings, const Ximu3SettingsIndex index) {{
    const Metadata metadata = {{
        .name = names[index],
        .key = keys[index],
        .value = GetValue(settings, index),
        .type = types[index],
        .size = sizes[index],
        .defaultValue = defaults[index],
        .preserved = preserveds[index],
        .readOnly = readOnlys[index],
        .applied = &settings->applied[index],
    }};
    return metadata;
}}
"""

Path("Metadata.c").write_text(contents)
