/**
 * @file Ximu3Size.h
 * @author Seb Madgwick
 * @brief Maximum sizes for memory allocation.
 */

#ifndef XIMU3_SIZE_H
#define XIMU3_SIZE_H

//------------------------------------------------------------------------------
// Definitions

#define XIMU3_SIZE_READ                         (2048)
#define XIMU3_SIZE_COMMAND                      (1024)
#define XIMU3_SIZE_KEY                          (64)
#define XIMU3_SIZE_VALUE                        (512)
#define XIMU3_SIZE_MUX_HEADER                   (2)

#define XIMU3_SIZE_CHAR_ARRAY                   (255)

#define XIMU3_SIZE_BYTE_STUFFING(n)             (2 * (n)) /* worst case after byte stuffing */

#define XIMU3_SIZE_BINARY_OVERHEAD              (2 + XIMU3_SIZE_BYTE_STUFFING(8)) /* ID + termination + 64-bit timestamp */
#define XIMU3_SIZE_BINARY_FLOAT                 XIMU3_SIZE_BYTE_STUFFING(4) /* 32-bit float */
#define XIMU3_SIZE_BINARY_CHAR_ARRAY            XIMU3_SIZE_BYTE_STUFFING(XIMU3_SIZE_CHAR_ARRAY)

#define XIMU3_SIZE_BINARY_INERTIAL              (XIMU3_SIZE_BINARY_OVERHEAD + (6 * XIMU3_SIZE_BINARY_FLOAT))
#define XIMU3_SIZE_BINARY_MAGNETOMETER          (XIMU3_SIZE_BINARY_OVERHEAD + (3 * XIMU3_SIZE_BINARY_FLOAT))
#define XIMU3_SIZE_BINARY_HIGH_G_ACCELEROMETER  (XIMU3_SIZE_BINARY_OVERHEAD + (3 * XIMU3_SIZE_BINARY_FLOAT))
#define XIMU3_SIZE_BINARY_QUATERNION            (XIMU3_SIZE_BINARY_OVERHEAD + (4 * XIMU3_SIZE_BINARY_FLOAT))
#define XIMU3_SIZE_BINARY_ROTATION_MATRIX       (XIMU3_SIZE_BINARY_OVERHEAD + (9 * XIMU3_SIZE_BINARY_FLOAT))
#define XIMU3_SIZE_BINARY_EULER_ANGLES          (XIMU3_SIZE_BINARY_OVERHEAD + (3 * XIMU3_SIZE_BINARY_FLOAT))
#define XIMU3_SIZE_BINARY_LINEAR_ACCELERATION   (XIMU3_SIZE_BINARY_OVERHEAD + (7 * XIMU3_SIZE_BINARY_FLOAT))
#define XIMU3_SIZE_BINARY_EARTH_ACCELERATION    (XIMU3_SIZE_BINARY_OVERHEAD + (7 * XIMU3_SIZE_BINARY_FLOAT))
#define XIMU3_SIZE_BINARY_AHRS_STATUS           (XIMU3_SIZE_BINARY_OVERHEAD + (4 * XIMU3_SIZE_BINARY_FLOAT))
#define XIMU3_SIZE_BINARY_SERIAL_ACCESSORY      (XIMU3_SIZE_BINARY_OVERHEAD + XIMU3_SIZE_BINARY_CHAR_ARRAY)
#define XIMU3_SIZE_BINARY_SYNC                  (XIMU3_SIZE_BINARY_OVERHEAD + XIMU3_SIZE_BINARY_FLOAT)
#define XIMU3_SIZE_BINARY_LTC                   (XIMU3_SIZE_BINARY_OVERHEAD + sizeof ("hh:mm:ss:ff") - 1) /* byte stuffing not applicable to timecode */
#define XIMU3_SIZE_BINARY_TEMPERATURE           (XIMU3_SIZE_BINARY_OVERHEAD + XIMU3_SIZE_BINARY_FLOAT)
#define XIMU3_SIZE_BINARY_BATTERY               (XIMU3_SIZE_BINARY_OVERHEAD + (3 * XIMU3_SIZE_BINARY_FLOAT))
#define XIMU3_SIZE_BINARY_RSSI                  (XIMU3_SIZE_BINARY_OVERHEAD + (2 * XIMU3_SIZE_BINARY_FLOAT))
#define XIMU3_SIZE_BINARY_BUTTON                (XIMU3_SIZE_BINARY_OVERHEAD + XIMU3_SIZE_BINARY_FLOAT)
#define XIMU3_SIZE_BINARY_NOTIFICATION          (XIMU3_SIZE_BINARY_OVERHEAD + XIMU3_SIZE_BINARY_CHAR_ARRAY)
#define XIMU3_SIZE_BINARY_ERROR                 (XIMU3_SIZE_BINARY_OVERHEAD + XIMU3_SIZE_BINARY_CHAR_ARRAY)

#define XIMU3_SIZE_ASCII_OVERHEAD           	(sizeof ("X,00112233445566778899\n") - 1)
#define XIMU3_SIZE_ASCII_FLOAT              	(sizeof (",-999999.9999") - 1)
#define XIMU3_SIZE_ASCII_CHAR_ARRAY             (sizeof (",") - 1 + XIMU3_SIZE_CHAR_ARRAY)

#define XIMU3_SIZE_ASCII_INERTIAL           	(XIMU3_SIZE_ASCII_OVERHEAD + (6 * XIMU3_SIZE_ASCII_FLOAT))
#define XIMU3_SIZE_ASCII_MAGNETOMETER       	(XIMU3_SIZE_ASCII_OVERHEAD + (3 * XIMU3_SIZE_ASCII_FLOAT))
#define XIMU3_SIZE_ASCII_HIGH_G_ACCELEROMETER   (XIMU3_SIZE_ASCII_OVERHEAD + (3 * XIMU3_SIZE_ASCII_FLOAT))
#define XIMU3_SIZE_ASCII_QUATERNION         	(XIMU3_SIZE_ASCII_OVERHEAD + (4 * XIMU3_SIZE_ASCII_FLOAT))
#define XIMU3_SIZE_ASCII_ROTATION_MATRIX    	(XIMU3_SIZE_ASCII_OVERHEAD + (9 * XIMU3_SIZE_ASCII_FLOAT))
#define XIMU3_SIZE_ASCII_EULER_ANGLES       	(XIMU3_SIZE_ASCII_OVERHEAD + (3 * XIMU3_SIZE_ASCII_FLOAT))
#define XIMU3_SIZE_ASCII_LINEAR_ACCELERATION	(XIMU3_SIZE_ASCII_OVERHEAD + (7 * XIMU3_SIZE_ASCII_FLOAT))
#define XIMU3_SIZE_ASCII_EARTH_ACCELERATION 	(XIMU3_SIZE_ASCII_OVERHEAD + (7 * XIMU3_SIZE_ASCII_FLOAT))
#define XIMU3_SIZE_ASCII_AHRS_STATUS        	(XIMU3_SIZE_ASCII_OVERHEAD + (4 * XIMU3_SIZE_ASCII_FLOAT))
#define XIMU3_SIZE_ASCII_SERIAL_ACCESSORY   	(XIMU3_SIZE_ASCII_OVERHEAD + XIMU3_SIZE_ASCII_CHAR_ARRAY)
#define XIMU3_SIZE_ASCII_SYNC               	(XIMU3_SIZE_ASCII_OVERHEAD + (1 * XIMU3_SIZE_ASCII_FLOAT))
#define XIMU3_SIZE_ASCII_LTC                	(XIMU3_SIZE_ASCII_OVERHEAD + sizeof (",hh:mm:ss:ff") - 1)
#define XIMU3_SIZE_ASCII_TEMPERATURE        	(XIMU3_SIZE_ASCII_OVERHEAD + (1 * XIMU3_SIZE_ASCII_FLOAT))
#define XIMU3_SIZE_ASCII_BATTERY            	(XIMU3_SIZE_ASCII_OVERHEAD + (3 * XIMU3_SIZE_ASCII_FLOAT))
#define XIMU3_SIZE_ASCII_RSSI               	(XIMU3_SIZE_ASCII_OVERHEAD + (2 * XIMU3_SIZE_ASCII_FLOAT))
#define XIMU3_SIZE_ASCII_BUTTON             	(XIMU3_SIZE_ASCII_OVERHEAD + (1 * XIMU3_SIZE_ASCII_FLOAT))
#define XIMU3_SIZE_ASCII_NOTIFICATION       	(XIMU3_SIZE_ASCII_OVERHEAD + XIMU3_SIZE_ASCII_CHAR_ARRAY)
#define XIMU3_SIZE_ASCII_ERROR              	(XIMU3_SIZE_ASCII_OVERHEAD + XIMU3_SIZE_ASCII_CHAR_ARRAY)

#define XIMU3_SIZE_MAX(a, b)                    ((a) > (b) ? (a) : (b))

#define XIMU3_SIZE_INERTIAL                     XIMU3_SIZE_MAX(XIMU3_SIZE_BINARY_INERTIAL, XIMU3_SIZE_ASCII_INERTIAL)
#define XIMU3_SIZE_MAGNETOMETER                 XIMU3_SIZE_MAX(XIMU3_SIZE_BINARY_MAGNETOMETER, XIMU3_SIZE_ASCII_MAGNETOMETER)
#define XIMU3_SIZE_HIGH_G_ACCELEROMETER         XIMU3_SIZE_MAX(XIMU3_SIZE_BINARY_HIGH_G_ACCELEROMETER, XIMU3_SIZE_ASCII_HIGH_G_ACCELEROMETER)
#define XIMU3_SIZE_QUATERNION                   XIMU3_SIZE_MAX(XIMU3_SIZE_BINARY_QUATERNION, XIMU3_SIZE_ASCII_QUATERNION)
#define XIMU3_SIZE_ROTATION_MATRIX              XIMU3_SIZE_MAX(XIMU3_SIZE_BINARY_ROTATION_MATRIX, XIMU3_SIZE_ASCII_ROTATION_MATRIX)
#define XIMU3_SIZE_EULER_ANGLES                 XIMU3_SIZE_MAX(XIMU3_SIZE_BINARY_EULER_ANGLES, XIMU3_SIZE_ASCII_EULER_ANGLES)
#define XIMU3_SIZE_LINEAR_ACCELERATION          XIMU3_SIZE_MAX(XIMU3_SIZE_BINARY_LINEAR_ACCELERATION, XIMU3_SIZE_ASCII_LINEAR_ACCELERATION)
#define XIMU3_SIZE_EARTH_ACCELERATION           XIMU3_SIZE_MAX(XIMU3_SIZE_BINARY_EARTH_ACCELERATION, XIMU3_SIZE_ASCII_EARTH_ACCELERATION)
#define XIMU3_SIZE_AHRS_STATUS                  XIMU3_SIZE_MAX(XIMU3_SIZE_BINARY_AHRS_STATUS, XIMU3_SIZE_ASCII_AHRS_STATUS)
#define XIMU3_SIZE_SERIAL_ACCESSORY             XIMU3_SIZE_MAX(XIMU3_SIZE_BINARY_SERIAL_ACCESSORY, XIMU3_SIZE_ASCII_SERIAL_ACCESSORY)
#define XIMU3_SIZE_SYNC                         XIMU3_SIZE_MAX(XIMU3_SIZE_BINARY_SYNC, XIMU3_SIZE_ASCII_SYNC)
#define XIMU3_SIZE_LTC                          XIMU3_SIZE_MAX(XIMU3_SIZE_BINARY_LTC, XIMU3_SIZE_ASCII_LTC)
#define XIMU3_SIZE_TEMPERATURE                  XIMU3_SIZE_MAX(XIMU3_SIZE_BINARY_TEMPERATURE, XIMU3_SIZE_ASCII_TEMPERATURE)
#define XIMU3_SIZE_BATTERY                      XIMU3_SIZE_MAX(XIMU3_SIZE_BINARY_BATTERY, XIMU3_SIZE_ASCII_BATTERY)
#define XIMU3_SIZE_RSSI                         XIMU3_SIZE_MAX(XIMU3_SIZE_BINARY_RSSI, XIMU3_SIZE_ASCII_RSSI)
#define XIMU3_SIZE_BUTTON                       XIMU3_SIZE_MAX(XIMU3_SIZE_BINARY_BUTTON, XIMU3_SIZE_ASCII_BUTTON)
#define XIMU3_SIZE_NOTIFICATION                 XIMU3_SIZE_MAX(XIMU3_SIZE_BINARY_NOTIFICATION, XIMU3_SIZE_ASCII_NOTIFICATION)
#define XIMU3_SIZE_ERROR                        XIMU3_SIZE_MAX(XIMU3_SIZE_BINARY_ERROR, XIMU3_SIZE_ASCII_ERROR)

#endif

//------------------------------------------------------------------------------
// End of file
